name = "aethereal-engineering"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd106af43b150590715fb031fbdbb58a484a036ab908ce60a4455590397abaea"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
