name = "aethereal-engineering"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "435e26767840096a65f3bf094294a232bf9cd2282eec2dec064d9fdd251adbd2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
