name = "aethereal-engineering"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19507c6ecdb2f031326eacdc5d4db8e7aa5a692716c58991ef22ef579100c6f3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
