name = "aethereal-engineering"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54ced82107448e3b63f96de30bba12b9b66ebbb7e60fd302d2fedbe7012831a5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
