name = "aethereal-engineering"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "573747a56bbd5973f647c8f12033c2c38f2a18a41c5fa68f55f0d1ddc9d59b4f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
